### PR TITLE
Add functionality to scan network and discover hubs

### PR DESCRIPTION
**Pull request by tony2nite**
Run `pyharmony --discover` to try to find hubs on network and return hub config details. In theory it should handle finding multiple hubs if you have them but I don't have multiple hubs to test with.

### CODE REVIEW

**Comment by iandday** [comment]
Hi Tony,

This is a great feature, unfortunately it only found one of the two hubs on my network each time I ran it.  It found each hub individually, but not both during the same execution.  How can I help troubleshoot this?

**Comment by tony2nite** [comment]
@iandday, yep reviewing it now, there is something wrong with the collection of hubs. Even with one hub, I would expect the same hub to be found at every ping, but at the moment it seems to be found once, and never again. Let me see if I can iron out that problem with one hub.

FYI I've created [this pull request](https://github.com/home-assistant/netdisco/pull/107) on Home Assistant's `netdisco` library to use make Harmony SSDP discoverable, so just in regards to getting Harmony Remote discovery working on Home Assistant (eventually) the netdisco approach might end up being simpler.

**Comment by tony2nite** [comment]
@iandday please try again with the latest update to see if you get all your hubs discovered

**Comment by iandday** [comment]
It's hanging for me until I interuptt it.  Here's the trace

localadmin@Dev:~/test/pyharmony$ python3 pyharmony --discover --loglevel DEBUG
^CTraceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "pyharmony/__main__.py", line 479, in <module>
    main()
  File "pyharmony/__main__.py", line 473, in main
    sys.exit(discover(args))
  File "pyharmony/__main__.py", line 397, in discover
    hubs = harmony_discovery.discover()
  File "/usr/local/lib/python3.5/dist-packages/pyharmony-1.0.12-py3.5.egg/pyharmony/discovery.py", line 110, in discover
    return Discovery().discover(scan_attempts, scan_interval)
  File "/usr/local/lib/python3.5/dist-packages/pyharmony-1.0.12-py3.5.egg/pyharmony/discovery.py", line 76, in discover
    client_connection, client_address = listen_socket.accept()
  File "/usr/lib/python3.5/socket.py", line 195, in accept
    fd, addr = self._accept()
KeyboardInterrupt

**Comment by tony2nite** [comment]
I've tweaked the logging to try and get some more info out of what's happening for you. The scan should take 10 seconds then stop.

You could try unplugging one of your hubs while you test the scan to see if it really is related to the two hubs or it's another issue.

I've been testing on OSX on python 3.5.1. What system are you working on?

**Comment by iandday** [comment]
It looks like it found both of my hubs successfully, still hanging though until I break it.  I'm running python 3.5.2 on a virtualized instance of Ubuntu 14.04 LTS

```
localadmin@Dev:~/test/pyharmony$ python3 pyharmony --discover --loglevel DEBUG
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Found new hub f183f0af-2b0a-44e3-1542-764a811dc1d8
DEBUG:  pyharmony.discovery     Found new hub a9238f72-92a0-4652-1cce-b1eaba302e38
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Found existing hub f183f0af-2b0a-44e3-1542-764a811dc1d8
DEBUG:  pyharmony.discovery     Found existing hub a9238f72-92a0-4652-1cce-b1eaba302e38
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Found existing hub a9238f72-92a0-4652-1cce-b1eaba302e38
DEBUG:  pyharmony.discovery     Found existing hub f183f0af-2b0a-44e3-1542-764a811dc1d8
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Found existing hub f183f0af-2b0a-44e3-1542-764a811dc1d8
DEBUG:  pyharmony.discovery     Found existing hub a9238f72-92a0-4652-1cce-b1eaba302e38
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Found existing hub f183f0af-2b0a-44e3-1542-764a811dc1d8
DEBUG:  pyharmony.discovery     Found existing hub a9238f72-92a0-4652-1cce-b1eaba302e38
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Found existing hub f183f0af-2b0a-44e3-1542-764a811dc1d8
DEBUG:  pyharmony.discovery     Found existing hub a9238f72-92a0-4652-1cce-b1eaba302e38
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Found existing hub f183f0af-2b0a-44e3-1542-764a811dc1d8
DEBUG:  pyharmony.discovery     Found existing hub a9238f72-92a0-4652-1cce-b1eaba302e38
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Found existing hub a9238f72-92a0-4652-1cce-b1eaba302e38
DEBUG:  pyharmony.discovery     Found existing hub f183f0af-2b0a-44e3-1542-764a811dc1d8
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Found existing hub f183f0af-2b0a-44e3-1542-764a811dc1d8
DEBUG:  pyharmony.discovery     Found existing hub a9238f72-92a0-4652-1cce-b1eaba302e38
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Found existing hub f183f0af-2b0a-44e3-1542-764a811dc1d8
DEBUG:  pyharmony.discovery     Found existing hub a9238f72-92a0-4652-1cce-b1eaba302e38
^CTraceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "pyharmony/__main__.py", line 483, in <module>
    main()
  File "pyharmony/__main__.py", line 477, in main
    sys.exit(discover(args))
  File "pyharmony/__main__.py", line 397, in discover
    hubs = harmony_discovery.discover()
  File "/usr/local/lib/python3.5/dist-packages/pyharmony-1.0.12-py3.5.egg/pyharmony/discovery.py", line 113, in discover
    return Discovery().discover(scan_attempts, scan_interval)
  File "/usr/local/lib/python3.5/dist-packages/pyharmony-1.0.12-py3.5.egg/pyharmony/discovery.py", line 79, in discover
    client_connection, client_address = listen_socket.accept()
  File "/usr/lib/python3.5/socket.py", line 195, in accept
    fd, addr = self._accept()
KeyboardInterrupt

```

**Comment by iandday** [comment]
we're getting there, it's back to discovering both hubs, but only one at a time, it reliable alternates between one of the two hubs each time i execute it


```
localadmin@Dev:~/test/pyharmony$ python3 pyharmony --discover --loglevel DEBUG
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Found new hub f183f0af-2b0a-44e3-1542-764a811dc1d8
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Pinging network on port 61991
INFO:   pyharmony.discovery     Completed scan, 1 hub(s) found.
[
    {
        "accountId": "6118599",
        "current_fw_version": "4.9.40",
        "discoveryServerUri": "http",
        "email": "iandday@gmail.com",
        "friendlyName": "BedRoom",
        "host_name": "BedRoom",
        "hubId": "97",
        "hubProfiles": "{Harmony=\"2.0\"}",
        "ip": "10.168.1.13",
        "minimumOpenApiClientVersionRequired": "1",
        "oohEnabled": "true",
        "openApiVersion": "2",
        "port": "5222",
        "productId": "Pimento",
        "protocolVersion": "{XMPP=\"1.0\", HTTP=\"1.0\", RF=\"1.0\", WEBSOCKET=\"1.0\"}",
        "recommendedOpenApiClientVersion": "1",
        "remoteId": "6171000",
        "setupSessionClient": "Mob-D1E63031-BD76-4D81-AD77-0A908D0E788A",
        "setupSessionIsStale": "true",
        "setupSessionSetupType": "",
        "setupSessionType": "0",
        "setupStatus": "0",
        "uuid": "f183f0af-2b0a-44e3-1542-764a811dc1d8"
    }
]
localadmin@Dev:~/test/pyharmony$ python3 pyharmony --discover --loglevel DEBUG
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Found new hub a9238f72-92a0-4652-1cce-b1eaba302e38
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Pinging network on port 61991
DEBUG:  pyharmony.discovery     Pinging network on port 61991
INFO:   pyharmony.discovery     Completed scan, 1 hub(s) found.
[
    {
        "accountId": "7578043",
        "current_fw_version": "4.12.36",
        "discoveryServerUri": "http",
        "email": "iandday@gmail.com",
        "friendlyName": "LivingRoom",
        "host_name": "LivingRoom",
        "hubId": "106",
        "hubProfiles": "{Harmony=\"2.0\"}",
        "ip": "10.168.1.16",
        "minimumOpenApiClientVersionRequired": "1",
        "mode": "3",
        "oohEnabled": "true",
        "openApiVersion": "2",
        "port": "5222",
        "productId": "Pimento",
        "protocolVersion": "{XMPP=\"1.0\", HTTP=\"1.0\", RF=\"1.0\", WEBSOCKET=\"1.0\"}",
        "recommendedOpenApiClientVersion": "1",
        "remoteId": "7951975",
        "setupSessionClient": "Mob-49cead43-a39b-41aa-a1a1-6ba470c2b0b7",
        "setupSessionIsStale": "true",
        "setupSessionSetupType": "",
        "setupSessionType": "0",
        "setupStatus": "0",
        "uuid": "a9238f72-92a0-4652-1cce-b1eaba302e38"
    }
]
localadmin@Dev:~/test/pyharmony$
```

**Comment by iandday** [comment]
nicely done!!
```

localadmin@Dev:~/test/pyharmony$ python3 pyharmony --discover
INFO:   pyharmony.discovery     Completed scan, 2 hub(s) found.
```

I'm going to merge this and bump the version number, this will be cool to integrate into HASS

**Comment by tony2nite** [comment]
Great. Got there in the end.

As I mentioned above, regarding HASS, I have a rough version using netdisco as the detection method which may end up being more robust. Check out the WIP [here](https://github.com/home-assistant/home-assistant/compare/dev...tony2nite:harmony-auto-discovery)

**Pull request merged**
