### PR TITLE
Add optional callback for activity changes

### PR DESCRIPTION
**Pull request by amelchio**
This allows the client to know about external activity changes as soon as they are reported by the Harmony Hub.

### CODE REVIEW

**Comment by amelchio** [comment]
Hi @iandday!

Can you please let us know whether this repo is still maintained?

I would prefer not to create another fork so please take a little time within the next week to let us know the status of your project .

Thanks!

**Comment by iandday** [comment]
Hi amelchio,
I was traveling for work this week and didnt have any time to look through these, I just browsed through the code changes and they look great!  I'm going to take a closer look tomorrow and try them out on my hubs.  If all goes well i'll push the new version, it'll be great to see the new functions in hass

**Comment by amelchio** [comment]
That's great to hear! There is no rush, just didn't want to wait indefinitely :)

**Comment by iandday** [comment]
these changes look great, thank you.

I removed the token functionality completely from all ha_* functions.  I'm going to publish this as 1.0.17, there doesnt look to be to many changes to be made on the HASS module to remove all references to auth tokens.

**Comment by amelchio** [comment]
Thank you, that's very nice. I will get my Home Assistant PR updated so we can soon enjoy these improvements :)

**Pull request merged**
