### PR TITLE
Add ability to repeat a command or send a list of commands

### PR DESCRIPTION
**Pull request by everix1992**
The idea here is to add direct support into pyharmony for sending multiple commands at once to reduce the delay in sending these commands. You could sort of replicate the same behavior in Home Assistant before, but it was unideal to connect and disconnect from the client for each command being sent.

Some potential use cases for this are sending multiple volume up commands at once, changing the channel (i.e. sending the commands 'Channel7', 'Channel1', 'Channel5'), or pressing the channel/up down buttons.

The new parameters added to ha_send_command() were given a defaults to maintain compatibility.

### CODE REVIEW

**Comment by chrisjaure** [comment]
I definitely need this. I'm trying to adjust the volume on my audio receiver but the way it works is one volume command just displays the volume on the lcd and another command is needed to actually increase/decrease the volume. This second command needs to be sent within a second or two before the lcd reverts back to showing whatever it was before, and right now, the delay is just a few milliseconds too long and I can't actually change the volume by sending successive commands.

**Comment by everix1992** [comment]
I don't think the developer is monitoring this repository anymore. I may have to do a new release of pyharmony myself (if that's possible) if I don't hear anything from him soon.

**Comment by toshibochan** [comment]
How to install and use this?

**Comment by iandday** [comment]
your changes to the HASS harmony component look good!  I created a new release of pyharmony version 1.0.14 with your changes.  It looks like all you have left are the unit tests and to update the pyharmony version number in the requirements file.

**Comment by everix1992** [comment]
Awesome! I'll get it all updated for the current release and work on getting it pulled into the HASS mainline this week.

**Pull request merged**
